"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GUILDS = 1 << 0;
exports.GUILDS_MEMBERS = 1 << 1;
exports.GUILD_BANS = 1 << 2;
exports.GUILD_EMOJIS = 1 << 3;
exports.GUILD_INTEGRATIONS = 1 << 4;
exports.GUILD_WEBHOOKS = 1 << 5;
exports.GUILD_INVITES = 1 << 6;
exports.GUILD_VOICE_STATS = 1 << 7;
exports.GUILD_PRESENCES = 1 << 8;
exports.GUILD_MESSAGES = 1 << 9;
exports.GUILD_MESSAGES_REACTIONS = 1 << 10;
exports.GUILD_MESSAGE_TYPING = 1 << 11;
exports.DIRECT_MESSAGES = 1 << 12;
exports.DIRECT_MESSAGE_REACTIONS = 1 << 13;
exports.DIRECT_MESSAGE_TYPING = 1 << 14;
